# Generated by Django 4.1.1 on 2022-10-15 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact_View',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=200)),
                ('lastName', models.CharField(max_length=200)),
                ('emailAddress', models.EmailField(max_length=254)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='registerMosa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=200)),
                ('firstName', models.CharField(max_length=200)),
                ('lastName', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('phoneNumber', models.IntegerField()),
                ('nationality', models.CharField(max_length=200)),
                ('religion', models.CharField(max_length=200)),
                ('homeAddress', models.CharField(max_length=200)),
                ('occupation', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=250)),
                ('stateOfOrigin', models.CharField(max_length=200)),
            ],
        ),
    ]
